#version: '3.9'

services:
  postgres-students:
    image: postgres:latest
    container_name: spring-microservice-container
    environment:
      POSTGRES_DB: spring_ms
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-spring-data:/var/lib/postgresql/data
    restart: always


volumes:
  postgres-spring-data:
    driver: local